# Generated by Django 2.0.7 on 2021-07-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='static/img/shattered.png', upload_to='static/img')),
                ('name', models.CharField(max_length=1000)),
                ('spcialztion', models.CharField(max_length=500)),
                ('email', models.URLField(max_length=500)),
            ],
        ),
    ]
