# Generated by Django 2.0.7 on 2021-07-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='visit',
            field=models.FileField(upload_to='media'),
        ),
    ]
