# Generated by Django 2.0.7 on 2021-07-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0002_alter_artical_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
